### ISSUE TITLE
Using TLS without wolfSSL

### ISSUE THREAD

**Issue by denravonska** [wolfSSL/wolfMQTT#100]
I am trying a setup where I use OpenSSL when building on the PC and SSL enabled sockets on our modem chip when building for the target device. This seems to work fine and allows me to skip much of the SSL/TLS handling in the MCU, thus freeing up resources. 

Now I want to have the option to connect to TLS- and non-TLS servers, but the `use_tls` flag is never passed to the socket connect callback so there's no way to determine what type of connection to use. Is there a better way to use TLS without using wolfSSL?

**Comment by kaleb-himes** [comment]
Hi @denravonska,

Thank you for reaching out to wolfSSL with your questions. For better response time and status tracking of your inquiry please send your questions to support@wolfssl.com or register at wolfssl.zendesk.com. All questions sent to support@wolfssl.com are forwarded to our Zendesk domain where one of our engineers will gladly assist you!

Warm Regards,

- The wolfSSL Team

**Comment by dgarske** [comment]
Hi Marco,

Excellent suggestion. There should be a way to do this via the opaque void*. Let me see if I can do it and provide an example for it otherwise we’ll imolement an enhancement. A Github issue is appropriate for this. 

Thanks,
David Garske.

**Comment by denravonska** [comment]
My local modification passes the `use_tls` flag to the connect callback but that unfortunately breaks the API. Using the `void*` would be a cleaner solution in terms of API compatibility.

**Comment by denravonska** [comment]
The example in #101 worked perfectly.
