### ISSUE TITLE
run configure on linux error.

### ISSUE THREAD

**Issue by benhaz1024** [wolfSSL/wolfMQTT#106]
I clone wolfMQTT from github, then followed README:
> ./autogen.sh
>./configure

it give me error:
>configure: error: libwolfssl is required for wolfmqtt, .....

I try two methed:
1. install wolfssl using apt-get
2. build wolfssl and intall it, then run configure with option: --with-libwolfssl-prefix=/path/to/wolfssl/install

error still existed.

my linux version is : linuxmint 18.3 (it based on ubuntu 16.04, and I think it works same).

Thanks!

**Comment by embhorn** [comment]
Hello @benhaz1024 

Thanks for contacting support. The wolfMQTT library requires wolfSSL by default. I recommend installing wolfSSL using the default instructions:
https://github.com/wolfSSL/wolfssl/blob/master/INSTALL

Next update the library cache by running:
`sudo ldconfig`

Then try the installation for wolfMQTT.

If you do not require a secure connection using TLS, wolfMQTT can be configured with the `--disable-tls` option, which will remove the dependency on the wolfSSL library. Most of the wolfMQTT examples do require TLS.

Thanks,

Eric Blankenhorn
wolfSSL Support

**Comment by embhorn** [comment]
Hi @benhaz1024 

I hope this suggestion was helpful. Let us know if you have more questions!

Cheers,
Eric
