### ISSUE TITLE
MQTT_DATA_TYPE_BINARY  data len encoded twice

### ISSUE THREAD

**Issue by EdwinQian** [wolfSSL/wolfMQTT#113]
Function MqttEncode_Props must change like below:

 case MQTT_DATA_TYPE_BINARY:
            {
	**#if 0**			
                /* Binary type is a two byte integer "length"
                   followed by that number of bytes */
                tmp = MqttEncode_Num(buf, cur_prop->data_bin.len);
                rc += tmp;
                if (buf != NULL) {
                    buf += tmp;
                }
	**#endif**

                tmp = MqttEncode_Data(buf, (const byte*)cur_prop->data_bin.data,
                        cur_prop->data_bin.len);
                rc += tmp;
                if (buf != NULL) {
                    buf += tmp;
                }
                break;
            }

**Comment by embhorn** [comment]
Hi @EdwinQian 

Thank you for the defect report. The fix has been merged in #114 

Best regards,
Eric Blankenhorn
wolfSSL Support
