### ISSUE TITLE
does it support esp32

### ISSUE THREAD

**Issue by milamber-ls** [wolfSSL/wolfMQTT#116]
how can I run the .\configure so I can compile it for esp32 (esp-idf)?

**Comment by kaleb-himes** [comment]
Hi @milamber-ls,

Have you ever heard of the the process termed "cross-compiling"? To cross compile on one system for another target system you need to acquire the appropriate toolchain that can compile for the target device. Once acquired you can setup a configure like so:

GENERIC EXAMPLE:

```
./configure \
CC="/path/to/your/toolchain/x-x-x-gcc" \
AR="/path/to/your/toolchain/x-x-x-ar" \
AS="/path/to/your/toolchain/x-x-x-gcc" \
RANLIB="/path/to/your/toolchain/x-x-x-ranlib" \
LD="/path/to/your/toolchain/x-x-x-ld" \
--host=<your host> \
<your other configure options here> \
CFLAGS="-mcpu=<your cpu definition here> \
<other cflags here>" \
LIBS="<libs>"
```

SPECIFIC EXAMPLE:

```
./configure \
CC="/usr/local/gcc_arm/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc" \
AR="/usr/local/gcc_arm/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-ar" \
AS="/usr/local/gcc_arm/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-gcc" \
RANLIB="/usr/local/gcc_arm/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-ranlib" \
LD="/usr/local/gcc_arm/gcc-arm-none-eabi-7-2017-q4-major/bin/arm-none-eabi-ld" \
--host=arm-none-eabi \
-enable-aesgcm --enable-ecc \
CFLAGS="-mcpu=cortex-m4 \
-Os -specs=rdimon.specs"  \
LIBS="-Wl,--start-group -lm -lgcc -lc -lrdimon -Wl,--end-group"
```

Regards,

KH

**Comment by milamber-ls** [comment]
yes I have. cross compiling didn't work in esp-idf for windows. I haved installed the Linux version of esp-idf and I managed to successfully execute autogen and configure scripts. thank you for sharing this.

**Comment by kaleb-himes** [comment]
@milamber-ls,

Not a problem, thank you for reaching out with your questions, it's always our pleasure to help any way we can.

If you have any other questions you can reach our support staff for best response times at support@wolfssl.com or through wolfssl.zendesk.com.

Cheers,

KH
