### ISSUE TITLE
Compiling Examples

### ISSUE THREAD

**Issue by prateek-khatri** [wolfSSL/wolfMQTT#120]
Hello,

I installed WolfSSL and WolfMQTT on my Ubuntu 18.06 LTS, however there is no instructions on how to get the examples compiled and running.
Can you please point me to any documentation pertaining compilation of examples? (Also, same for when I write my own client).

`prateekkhatri@PC-10307:~/work/wolf/wolfMQTT/examples/mqttclient$ gcc mqttclient.c -o mqtt-test-wolf -lwolfmqtt
In file included from mqttclient.c:29:0:
mqttclient.h:25:10: fatal error: examples/mqttexample.h: No such file or directory
 #include "examples/mqttexample.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

Thanks,
Prateek

**Comment by kaleb-himes** [comment]
Hi @prateek-khatri,

Please see the "Building on *NIX" section of the wolfMQTT manual here: https://www.wolfssl.com/docs/wolfmqtt-manual/#h.o1z7uhcww9nn

The examples should be built with the execution of ./configure && make

For documentation on using/testing each of the examples see Chapter 3 "Getting Started" here: https://www.wolfssl.com/docs/wolfmqtt-manual/#h.9dbjm2iigup4

Warm Regards,

KH

**Comment by dgarske** [comment]
Hi Prateek-khatri,

```c
./autogen.sh
./configure
make
```

Here is our user manual:
https://www.wolfssl.com/docs/wolfmqtt-manual/
https://www.wolfssl.com/documentation/wolfMQTT-Manual.pdf

Thanks,
David Garske, wolfSSL

**Comment by prateek-khatri** [comment]
Hi Kaleb, David,

Thanks for the exact link. I was able to run the example client. I think I missed it in the manual.

Prateek
