### ISSUE TITLE
Is it possible to specify physical interface for MQTT to use?

### ISSUE THREAD

**Issue by prateek-khatri** [wolfSSL/wolfMQTT#123]
We are planning to have different interfaces on our board and one of the interface would have internet connectivity. 
Is it possible to specify what physical interface to use while creating the client and connecting? I couldn't explicitly find this in the documentation.

**Comment by dgarske** [comment]
Hi @prateek-khatri,

The physical interface can be anything. We have a reference UART example for the communication callbacks you can use here:
https://github.com/wolfSSL/wolfMQTT/blob/master/examples/mqttuart.c

Thanks,
David Garske, wolfSSL

**Comment by prateek-khatri** [comment]
Hi David,

Thanks for the example. However, I need a little bit more clarification. What I meant by physical interface was that in our Linux system we are adding multiple VLANs and multiple Ethernet interfaces - example: `eth0` , `eth1` etc.

On line 91 for the example code you pointed out:
```
        net->connect = NetConnect;
        net->read = NetRead;
        net->write = NetWrite;
        net->disconnect = NetDisconnect;
        net->context = WOLFMQTT_MALLOC(sizeof(UartContext));
```
In our use case, would the connect callback simply bind to the socket on the interface we specify using setsocketopt, and read callback would have recvfrom that socket?

Thanks,
Prateek

**Comment by dgarske** [comment]
Hi @prateek-khatri,

With the callbacks you can provide your own `net->context`, which can be different depending on the interface (eth0, eth1). Then your callbacks can be written the same and use the context to know the interface to use. Your `net->context` can provide a socket file descriptor bound to the physical interface.

Thanks,
David Garske, wolfSSL

**Comment by prateek-khatri** [comment]
Hi @dgarske 

```
Then your callbacks can be written the same and use the context to know the interface to use.
```
When we init the client using:
```
/* init defaults */
    mqtt_init_ctx(&mqttCtx);
```
Could I just specify the socket descriptor and leverage on the default callbacks or I still have to write my own?

Thanks,
Prateek
