### ISSUE TITLE
WOLFMQTT_NONBLOCK - Multithreaded - Clarification

### ISSUE THREAD

**Issue by prateek-khatri** [wolfSSL/wolfMQTT#124]
Hello,

The user manual lacks a lot of information on what WOLFMQTT_NONBLOCK does. Looking at the multithreading example:
https://github.com/wolfSSL/wolfMQTT/blob/4473d7b03dd8c3b01ffc85970e20ec28b6b8b930/examples/multithread/multithread.c#L458

The MQTTCtx structure is only available if NONBLOCK is not enabled?
Can you please provide more information on what NONBLOCK is doing?

Also, looking at example 5.3 in the user manual for MqttClient_Connect(...) it doesn't specify the broker IP anywhere. Please advise.

Also, MQTTCtx is not being recognized by the compiler? Do I have to include any other specific header file? 
To call the `int MqttClientNet_Init(MqttNet* net, MQTTCtx* mqttCtx)` function, I would need to populate MQTTCtx structure.

**Comment by dgarske** [comment]
Hi @prateek-khatri ,

The `MqttClientNet_Init` is a function in the example directory `mqttnet.c` and is meant to be customized for your own use.

You can find the reference example here:
https://github.com/wolfSSL/wolfMQTT/blob/master/examples/mqttnet.c#L960

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi @prateek-khatri ,

The `WOLFMQTT_NONBLOCK` option enables support for the network callbacks to return `MQTT_CODE_CONTINUE` and return up to caller this return code. Then you can call the MqttClient_* function again. The only example that implements non-blocking is the `nbclient` on located here:
https://github.com/wolfSSL/wolfMQTT/blob/master/examples/nbclient/nbclient.c

The wolfMQTT user manual is here:
https://www.wolfssl.com/docs/wolfmqtt-manual/

Search for `WOLFMQTT_NONBLOCK` to find usages with each MqttClient_* function it applies to.

Thanks,
David Garske, wolfSSL

**Comment by prateek-khatri** [comment]
Hi David,

Thanks for the response. I am still trying to wrap my head around the library. Having used paho-mqtt, it was much straightforward to navigate through their doxygen documentation. Is ther doxygen based documentation for the library source?

By looking at the user manual or examples (which are very different from one another) it is still not clear to me how I can achieve to write a simple MQTT Publisher from scratch using WolfMQTT. I am very confused as to which functions are to be implemented by me and which are present in the API. 

Looking at the mqttclient example:
https://github.com/wolfSSL/wolfMQTT/blob/4473d7b03dd8c3b01ffc85970e20ec28b6b8b930/examples/mqttclient/mqttclient.c#L609-L610

Does the above two lines mean that MQTTCtx should only be used when WOLFMQTT_NOBLOCK is disabled? If I am to use the NOBLOCK option then how do I provide the context to the MqttNet structure?

I want to achieve the following:
1. A simple MQTT Publisher - configuring broker IP, port, QOS, timeout, topic, client id etc.
2. A multithreaded MQTT Publisher - with multiple clients connecting.
3. A multithreaded MQTT Publisher with NOBLOCK enabled.
4. A multithreaded MQTT Publisher with NOBLOCK with a specific context provided.

Thank you for your patience and helping me out through this. 

We are also in process of purchasing a commercial license for WolfSSL and WolfMQTT but this evaluation is a key aspect to that decision.

**Comment by dgarske** [comment]
Hi @prateek-khatri,

That is a complex use-case. I think a conference call would be helpful. Please send an email to us at support@wolfssl.com with your contact information.

You would need to use parts of the multi-threading and non-blocking examples. The library proper code / API's are in the `src` and `wolfmqtt` directories. Everything the `examples` directory is reference code that is meant to be customized for your end application.

The non-blocking is useful for non-threaded / bare metal systems were the socket cannot block. Using non-blocking in a thread doesn't make sense unless you are monitoring multiple broker connections / sockets.

Thanks,
David Garske, wolfSSL
