### ISSUE TITLE
wolfMQTT Azure iotEdge communication 

### ISSUE THREAD

**Issue by Ilheu** [wolfSSL/wolfMQTT#125]
Hi, 
I'm trying to use wolfMQTT to communicate with an Azure IotEdge device, used as an transparent gateway ( https://docs.microsoft.com/en-us/azure/iot-edge/how-to-create-transparent-gateway ) ... I've already seen your examples with Azure iotHub, but to communicate with iotedge, there are some differences which I cannot get fixed ... Do you have any idea, example or something that I could use as an example ?

**Comment by dgarske** [comment]
Hi @Ilheu,

I reviewed the IoT edge gateway link you sent. It looks like you'll need to make sure you have the certificate and key setup correctly. Can you provide us some additional details for the command and errors you are seeing? If you'd like to keep the information private you can send us an email at support@wolfssl.com.

Thanks,
David Garske, wolfSSL
