### ISSUE TITLE
How can I specify a cipher suite?

### ISSUE THREAD

**Issue by aimproxy** [wolfSSL/wolfMQTT#140]

**Comment by dgarske** [comment]
Hi aimproxy,

We currently don't have a command line option for it, but you can add the following code in the `mqtt_tls_cb` function here: https://github.com/wolfSSL/wolfMQTT/blob/master/examples/mqttexample.c#L486

```c
/* use list of ciphers separated with colon ":" */
wolfSSL_CTX_set_cipher_list(client->tls.ctx, "ECDHE-ECDSA-AES128-GCM-SHA256")
```

You can get a list of wolfSSL ciphers using `wolfSSL_get_ciphers`. Here is an example:
https://github.com/wolfSSL/wolfssl/blob/master/examples/client/client.c#L196

Thanks,
David Garske, wolfSSL

**Comment by aimproxy** [comment]
Thx, it worked for me, but I have now another problem, this: MQTT Error -8: Error (Network), whats that mean?

**Comment by dgarske** [comment]
Hi @aimproxy ,

That is a generic error indicating network failure. My best guess would be that the TLS server on the broker closed the socket during the handshake. You can define the following build macros to get more information:

```c
#define WOLFMQTT_DEBUG_CLIENT
#define WOLFMQTT_DEBUG_SOCKET
```

On the wolfSSL side you can build with `./configure --enable-debug` or `DEBUG_WOLFSSL` to get verbose TLS logging.

Also if you get a Wireshark trace that would be helpful. Feel free to submit directly via our support@wolfssl.com ZenDesk system and reference this issue if you want it kept private.

Thanks,
David Garske, wolfSSL

**Comment by aimproxy** [comment]
Thx, I will see that

**Comment by aimproxy** [comment]
I got it, it was just the QOS! 
Thx anyway!
