### ISSUE TITLE
Error when building on Visual Studio 2019

### ISSUE THREAD

**Issue by kusumy** [wolfSSL/wolfMQTT#144]
There is an error message shows when building on the Visual Studio 2019:

Error	C1083	Cannot open include file: 'wolfmqtt/options.h': No such file or directory	awsiot	D:\Users\kusumy\Documents\Code\VStudio\wolfMQTT\wolfmqtt\mqtt_client.h	37		

Need help ..

**Comment by embhorn** [comment]
Hello @kusumy 

Thank you for contacting wolfSSL. This is a known issue with VS projects. We do not include the `options.h` file. You can simply copy `wolfmqtt/options.h.in` into a new file called `wolfmqtt/options.h`

We added a note at the source of the error to help guide VS users to this solution:

```
#if !defined(WOLFMQTT_USER_SETTINGS) && !defined(USE_WINDOWS_API)
    /* If options.h is missing use the "./configure" script. Otherwise, copy
     * the template "wolfmqtt/options.h.in" into "wolfmqtt/options.h" */
    #include <wolfmqtt/options.h>
#endif
```

Please let us know if you still have any issues!

Thanks,
Eric Blankenhorn
wolfSSL Support

**Comment by dgarske** [comment]
Hi @kusumy, did this resolve your Visual studio build issue?

Thanks,
David Garske, wolfSSL
