### ISSUE TITLE
Ping Message not trigged

### ISSUE THREAD

**Issue by dehmarc** [wolfSSL/wolfMQTT#157]
Hi there,

I was running your mqttsimple example with the mosquitto broker.

I realized the Ping request on the client was never triggered.

I investigated the issue and examined the problem to be the _mqtt_net_read_ function. In my opinion the socket timeout is never triggered, because it should be a _SO_RCVTIMEO_ timeout: https://github.com/wolfSSL/wolfMQTT/blob/423f243fafbd9baa10aeff6c52765f240005c318/examples/mqttsimple/mqttsimple.c#L225

Cheers,
Marc

**Comment by dgarske** [comment]
Hi Marc,

Thank you for that excellent bug report. We will push a fix shortly. 

Thanks,
David Garske, wolfSSL
