### ISSUE TITLE
Using MQTT v5 on Arduino

### ISSUE THREAD

**Issue by SjoerdC** [wolfSSL/wolfMQTT#180]
Hi,

We are using WolfMQTT as an Arduino library. This works great, except that we need to make a small manual adjustment to get MQTT v5 working. The following steps will reproduce the issue:

- Run ./autogen.sh
- Run ./configure with the --enable-mqtt5 flag and --disable-tls
- Run wolfmqtt-arduino.sh in the IDE/ARDUINO folder
- Move the resulting library to the Arduino libraries folder
- Compile the Arduino project

This will result in a lot of compilation errors:
```
In file included from Arduino/libraries/wolfMQTT/mqtt_packet.c:28:0:
Arduino/libraries/wolfMQTT/wolfmqtt/mqtt_client.h:360:2: error: unknown type name 'MqttAuth'
  MqttAuth *auth);
  ^
Arduino/libraries/wolfMQTT/wolfmqtt/mqtt_client.h:369:14: error: unknown type name 'MqttProp'
 WOLFMQTT_API MqttProp* MqttClient_PropsAdd(
              ^
Arduino/libraries/wolfMQTT/wolfmqtt/mqtt_client.h:370:5: error: unknown type name 'MqttProp'
     MqttProp **head);

....

```

These errors are generated because the WOLFMQTT_V5 macro is not defined in mqtt_packet.h, which will result in missing definitions.

**Possible solution:**
Change:
https://github.com/wolfSSL/wolfMQTT/blob/d02c8a7bf2aebaa6af5fc657d3d124b5e0cc1707/wolfmqtt/mqtt_types.h#L32-L34

Into:
`#include "options.h"`

This solves our problem and other users who use TLS don't have to uncomment that line anymore.

**Comment by embhorn** [comment]
Hello @SjoerdC 

Thanks for contacting wolfSSL support. I was able to reproduce this and I created #181 to address this issue.

We appreciate your feedback!

**Comment by SjoerdC** [comment]
Thanks, the issue is resolved now!
