### ISSUE TITLE
Publish using callback does not work with non-blocking mode.

### ISSUE THREAD

**Issue by embhorn** [wolfSSL/wolfMQTT#192]
The publish callback is used with `MqttClient_Publish_ex` and it currently uses `MQTT_CODE_CONTINUE` to indicate that the callback should process another block. The problem is that `MQTT_CODE_CONTINUE` is the return value from the non-block read / write to indicate the I/O should be called again. A new return code is needed to specify the condition that the callback should be executed again.

Reference: https://www.wolfssl.com/forums/topic1634-difficulty-using-mqttclientpublishex-with-pic32-harmony-300.html

**Comment by lygstate** [comment]
How about `MQTT_CODE_CALLBACK_CONTINUE `

**Comment by dgarske** [comment]
> How about `MQTT_CODE_CALLBACK_CONTINUE`

Yes that could work. Are you considering adding this feature?

**Comment by m-sauer** [comment]
Any progress on this?
