### ISSUE TITLE
Build on Windows fails because of options.h

### ISSUE THREAD

**Issue by tiolan** [wolfSSL/wolfMQTT#206]
I opened wolfmqtt.sln of release v1.8 in Visual Studio 2019, following the manual.
When building it fails:
`cannot open source file "wolfmqtt/options.h"	wolfmqtt	C:\src\src\wolfmqtt\wolfmqtt\mqtt_client.h	37	`

In `mqtt_client.h` there is
```
#if !defined(WOLFMQTT_USER_SETTINGS) && !defined(USE_WINDOWS_API)
    /* If options.h is missing use the "./configure" script. Otherwise, copy
     * the template "wolfmqtt/options.h.in" into "wolfmqtt/options.h" */
    #include <wolfmqtt/options.h>
#endif
#include "wolfmqtt/mqtt_types.h"
```

but `USE_WINDOWS_API` is defined in `mqtt_types.h`, that is included after `options.h`.
It seems `WOLFMQTT_USER_SETTINGS` is defined in the solution, but `USE_WINDOWS_API` not.

When changing the include order to `mqtt_types.h` before `options.h` it works.
Am I doing something wrong?

(Might also be the case when building other targets, I only build the target `wolfmqtt`)

**Comment by embhorn** [comment]
Hello Timo,

The `options.h` header file is expected to precede `mqtt_types.h`. As described in the comment you quoted above, the `options.h.in` file should be copied to `options.h` if it is missing.

Thanks,
@embhorn wolfSSL Support

**Comment by tiolan** [comment]
Understood. Because of `USE_WINDOWS_API` I though this applies only to Linux.

Thanks!
