### ISSUE TITLE
These three sem acceesed across the file in multiple place

### ISSUE THREAD

**Issue by lygstate** [wolfSSL/wolfMQTT#212]
wm_Sem lockSend;
    wm_Sem lockRecv;
    wm_Sem lockClient;

Can we merge these lockes in a single place?
Currently the lock/unlock procedure are interleaved with the state machine and hard to maintain and read.

**Comment by dgarske** [comment]
Hi @lygstate ,

There are separate locks so the socket can read and write at the same time in different threads. The socket send is locked with `lockSend`. The socket read is locked with `lockRecv`. The lockClient is just for the pending response add/remove/find to coordinate responses read from different threads.

Thanks,
David Garske, wolfSSL

**Comment by lygstate** [comment]
Good, make sense
