### ISSUE TITLE
Building for Arduino does not work.

### ISSUE THREAD

**Issue by apullin** [wolfSSL/wolfMQTT#22]
After following the README for flattening the files into an Arduino library and importing/including it with a minimal project, there is a build error.

Code is a bare minimum, with the library included. This is not expected to function, only to build to verify the library:

`
#include <mqttclient.h>
#include <mqttexample.h>
#include <mqttnet.h>
#include <wolfMQTT.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
`

However, the build/"verify" step produces the output with error listed below. The target is a simple Cortex M board, however the error is identical for any other ARM or AVR board.

`
/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/xyz/Library/Arduino15/packages -hardware /Users/xyz/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/xyz/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/xyz/Documents/Arduino/libraries -fqbn=adafruit:samd:adafruit_feather_m0 -ide-version=10801 -build-path /var/folders/dy/nsmz0p8s06b0z0_rrfvqtqz40000gn/T/arduino_build_239243 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.openocd.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/openocd/0.9.0-arduino -prefs=runtime.tools.arm-none-eabi-gcc.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1 -prefs=runtime.tools.bossac.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/bossac/1.6.1-arduino -prefs=runtime.tools.CMSIS.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel -verbose /Users/xyz/Documents/Arduino/sketches/wolfmqtt_test/wolfmqtt_test.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/xyz/Library/Arduino15/packages -hardware /Users/xyz/Documents/Arduino/hardware -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/xyz/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/xyz/Documents/Arduino/libraries -fqbn=adafruit:samd:adafruit_feather_m0 -ide-version=10801 -build-path /var/folders/dy/nsmz0p8s06b0z0_rrfvqtqz40000gn/T/arduino_build_239243 -warnings=none -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.openocd.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/openocd/0.9.0-arduino -prefs=runtime.tools.arm-none-eabi-gcc.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1 -prefs=runtime.tools.bossac.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/bossac/1.6.1-arduino -prefs=runtime.tools.CMSIS.path=/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel -verbose /Users/xyz/Documents/Arduino/sketches/wolfmqtt_test/wolfmqtt_test.ino
Using board 'adafruit_feather_m0' from platform in folder: /Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13
Using core 'arduino' from platform in folder: /Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13
Build options changed, rebuilding all
Detecting libraries used...
"/Users/xyz/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions  -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10801 -DARDUINO_SAMD_FEATHER_M0 -DARDUINO_ARCH_SAMD  -DARDUINO_SAMD_ZERO -D__SAMD21G18A__ -DUSB_VID=0x239A -DUSB_PID=0x800B -DUSBCON '-DUSB_MANUFACTURER="Adafruit"' '-DUSB_PRODUCT="Feather M0"' "-I/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel/CMSIS/Include/" "-I/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel/Device/ATMEL/" "-I/Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13/cores/arduino" "-I/Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13/variants/arduino_zero" "/var/folders/dy/nsmz0p8s06b0z0_rrfvqtqz40000gn/T/arduino_build_239243/sketch/wolfmqtt_test.ino.cpp" -o "/dev/null"
"/Users/xyz/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions  -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10801 -DARDUINO_SAMD_FEATHER_M0 -DARDUINO_ARCH_SAMD  -DARDUINO_SAMD_ZERO -D__SAMD21G18A__ -DUSB_VID=0x239A -DUSB_PID=0x800B -DUSBCON '-DUSB_MANUFACTURER="Adafruit"' '-DUSB_PRODUCT="Feather M0"' "-I/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel/CMSIS/Include/" "-I/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel/Device/ATMEL/" "-I/Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13/cores/arduino" "-I/Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13/variants/arduino_zero" "-I/Users/xyz/Documents/Arduino/libraries/wolfmqtt" "/var/folders/dy/nsmz0p8s06b0z0_rrfvqtqz40000gn/T/arduino_build_239243/sketch/wolfmqtt_test.ino.cpp" -o "/dev/null"
"/Users/xyz/Library/Arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/arm-none-eabi-g++" -mcpu=cortex-m0plus -mthumb -c -g -Os -w -std=gnu++11 -ffunction-sections -fdata-sections -fno-threadsafe-statics -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions  -w -x c++ -E -CC -DF_CPU=48000000L -DARDUINO=10801 -DARDUINO_SAMD_FEATHER_M0 -DARDUINO_ARCH_SAMD  -DARDUINO_SAMD_ZERO -D__SAMD21G18A__ -DUSB_VID=0x239A -DUSB_PID=0x800B -DUSBCON '-DUSB_MANUFACTURER="Adafruit"' '-DUSB_PRODUCT="Feather M0"' "-I/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel/CMSIS/Include/" "-I/Users/xyz/Library/Arduino15/packages/arduino/tools/CMSIS/4.0.0-atmel/Device/ATMEL/" "-I/Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13/cores/arduino" "-I/Users/xyz/Library/Arduino15/packages/adafruit/hardware/samd/1.0.13/variants/arduino_zero" "-I/Users/xyz/Documents/Arduino/libraries/wolfmqtt" "/var/folders/dy/nsmz0p8s06b0z0_rrfvqtqz40000gn/T/arduino_build_239243/sketch/wolfmqtt_test.ino.cpp" -o "/var/folders/dy/nsmz0p8s06b0z0_rrfvqtqz40000gn/T/arduino_build_239243/preproc/ctags_target_for_gcc_minus_e.cpp"
In file included from /Users/xyz/Documents/Arduino/sketches/wolfmqtt_test/wolfmqtt_test.ino:1:0:
/Users/xyz/Documents/Arduino/libraries/wolfmqtt/mqttclient.h:25:34: fatal error: examples/mqttexample.h: No such file or directory
 #include "examples/mqttexample.h"
                                  ^
compilation terminated.
Using library wolfmqtt in folder: /Users/xyz/Documents/Arduino/libraries/wolfmqtt (legacy)
exit status 1
Error compiling for board Adafruit Feather M0 (Native USB Port).`

**Comment by dgarske** [comment]
Fixes have been pushed to master. Let us know if you have any issues. Thanks
