### ISSUE TITLE
release artifact wolfmqtt-1.9.tar.gz is missing

### ISSUE THREAD

**Issue by chenrui333** [wolfSSL/wolfMQTT#228]
👋  just a heads up, it looks like the release artifact is missing for the 1.9 release.
![image](https://user-images.githubusercontent.com/1580956/127435145-2feee70a-a94c-497b-81c2-c44a5ac9737f.png)

**Comment by embhorn** [comment]
Hi @chenrui333 

I suppose you are referring to the `wolfMQTT-1.9.tar.gz` bundle, but this should be the same as clicking the `Source code
(tar.gz)` link
https://github.com/wolfSSL/wolfMQTT/archive/refs/tags/v1.9.tar.gz

I went ahead and added another link to the bundle to help clear up any confusion.
https://github.com/wolfSSL/wolfMQTT/releases/download/v1.9/wolfMQTT-1.9.tar.gz

Thanks,
@embhorn

**Comment by chenrui333** [comment]
yes, I was referring that `wolfMQTT-1.9.tar.gz` bundle, even though the artifact is pretty much the same, I think we can keep the tradition going. what do you think?

**Comment by chenrui333** [comment]
btw, thanks for the release artifact update.
