### ISSUE TITLE
Support for DTLS?

### ISSUE THREAD

**Issue by HendrikVE** [wolfSSL/wolfMQTT#275]
Since [paho.mqtt-sn.embedded-c](https://github.com/eclipse/paho.mqtt-sn.embedded-c) has support for DTLS it would be awesome if wolfMQTT had support for this as well. Are there any plans for this? As wolfMQTT uses wolfSSL, which supports DTLS, this looks like a perfect fit to me :P

**Comment by HendrikVE** [comment]
Nothing special I guess. Personally I would like to use DTLS for the `sn-client` using PSK and maybe also RPK which are also the options supported by RIOT and CoAP right now, but the paho gateway seems to only support X.509 at the moment. I hope adding e.g. PSK to paho should not be too complicated and I might take a look at it myself. I would be happy to support you with some testing feedback :)

**Comment by fj-blanco** [comment]
> Hello @HendrikVE
> 
> Yes! This is something we are discussing. Do you have any specific requirements for the DTLS encryption? Would you be able to provide feedback / testing?

I'm highly interested in DTLS support for MQTT-SN and Gateway/RSBM. I'm currently working on an academic project where this feature would be extremely useful. Is there any update on the timeline for DTLS support? I'd be more than happy to provide feedback and participate in testing.

Best ,

**Comment by embhorn** [comment]
Hi @fj-blanco 

The wolfMQTT client library for MQTT-SN added support for DTLS in the PR:
https://github.com/wolfSSL/wolfMQTT/pull/348

We'd love to hear your feedback!

@HendrikVE  - I'll go ahead and mark this issue as closed.

**Comment by embhorn** [comment]
@fj-blanco 

Right! We would need to write our own gateway, or modify the Paho MQTT-SN gateway to support wolfSSL.

I've created a new issue for this https://github.com/wolfSSL/wolfMQTT/issues/358
