### ISSUE TITLE
wolfMQTT ON STM32?

### ISSUE THREAD

**Issue by adz1122** [wolfSSL/wolfMQTT#28]
Would you like to ask if there is currently wolfMQTT support based on the STM32 mdk5 development environment? If not, can you make a set of references? We're going to use wolfMQTT on stm32.

**Comment by dgarske** [comment]
Hi adz1122,

We have an STM32F4 wolfMQTT demo based on the SystemWorkbench IDE by ST here:
https://www.wolfssl.com/files/demos/wolfSTM32.zip

We also have a wolfSSL example project for MDK5 here:
https://github.com/wolfSSL/wolfssl/tree/master/IDE/MDK5-ARM

Hopefully you can use these examples to build up something for wolfMQTT on that specific IDE and platform.

We also have an open pull request in wolfSSL for some STM32 improvements including the above SystemWorkbench example:
https://github.com/wolfSSL/wolfssl/pull/807

Let us know if you have any questions.

Thanks, David Garske, wolfSSL

**Comment by adz1122** [comment]
OK,I studied it, thank you
