### ISSUE TITLE
MqttSocket_Write "client->write.pos" not reset when socket write fail

### ISSUE THREAD

**Issue by trzhongty** [wolfSSL/wolfMQTT#289]
mqtt_socket.c
MqttSocket_Write

In blocking mode, "client->write.pos" is not reset when the "MqttSocket_WriteDo" result is less than 0. which in turn causes the wrong offset data to be sent when trying to reconnect, further errors until "client->write.pos >= buf_len"

Or should I have to clear client all on reconnect？

**Comment by embhorn** [comment]
Hi @trzhongty 

Yes, you are correct, the client structure should be re-initialized prior to attempting a reconnect due to an error or broker disconnect.

Thanks,
Eric @ wolfSSL Support

**Comment by trzhongty** [comment]
Thanks
