### ISSUE TITLE
Does it support esp8266? 

### ISSUE THREAD

**Issue by nerososft** [wolfSSL/wolfMQTT#33]

**Comment by dgarske** [comment]
Hi nerososft,

We do have customers using the ESP8266 module with wolfMQTT (and wolfSSL). 

I think you'll find our UART based example useful. It shows how to use a transport besides a socket as reference. This file is located here: https://github.com/wolfSSL/wolfMQTT/blob/master/examples/mqttuart.c

Let me know if that helps or if you have any other questions.

Thanks, David Garske

**Comment by nerososft** [comment]
got it, thank you very much, it‘s very helpful.
