### ISSUE TITLE
Broken wolfMQTT Cube Pack link

### ISSUE THREAD

**Issue by nandroidWB** [wolfSSL/wolfMQTT#359]
Hi, 

Could you update the  wolfMQTT Cube Pack link in [wolfMQTT for STM32 Cube IDE](https://github.com/wolfSSL/wolfMQTT/tree/master/IDE/STM32CUBE) please. I did not find in the _files_ section in the landing page as well.

Thanks in advance.

**Comment by embhorn** [comment]
Hi @nandroidWB 

We are working on fixing this issue with the website. In the meantime, you can use the curl CLI to get the cube pack

```
curl -LO https://www.wolfssl.com/files/ide/I-CUBE-wolfMQTT.pack
```

Thanks,
@embhorn

**Comment by embhorn** [comment]
@nandroidWB 

The cube pack file is available on the website now, and the link works. I will go ahead and close this issue.

Thanks,
@embhorn
