### ISSUE TITLE
Non-blocking solution?

### ISSUE THREAD

**Issue by PiedPieper** [wolfSSL/wolfMQTT#36]
Is there any plan to support a non-blocking api in the future? For most applications, it is important to be able to publish and subscribe at the same time.

**Comment by dgarske** [comment]
Hi PiedPieper,

We do support non-blocking mode using `./configure --enable-nonblock` or `#define WOLFMQTT_NONBLOCK`. This prevents any call from blocking and will return with `MQTT_CODE_CONTINUE`. This mode only works correctly in a single thread or if you manage the context between two threads yourself. With non-blocking mode you could accomplish your requirement.

I believe the feature you are requesting is multiple-thread support, which is at the top of our feature list to add.

Thanks,
David Garske, wolfSSL
