### ISSUE TITLE
Plans for supporting Direct Methods like in Azure IoT Hub

### ISSUE THREAD

**Issue by ChristianWeyer** [wolfSSL/wolfMQTT#38]
Hey there,

are you planning supporting Direct Methods, like here?
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods

Thanks.

**Comment by dgarske** [comment]
Hi Christian,

Our wolfMQTT library is built upon the MQTT 3.1.1 specification which allows any topic name.

The topic name syntax for direct methods for MQTT is:
Devices receive direct method requests on the MQTT topic: 
`$iothub/methods/POST/{method name}/?$rid={request id}`

You can see our Azure IoT example here:
https://github.com/wolfssl/wolfmqtt#azure-iot-hub-example
https://github.com/wolfSSL/wolfMQTT/blob/master/examples/azure/azureiothub.c#L72

So the short answer is yes it it supported with our library, but you will have to format the topic string yourself for the publish message.

Thanks,
David Garske, wolfSSL

**Comment by ChristianWeyer** [comment]
This is great. Thanks🤘

**Comment by ChristianWeyer** [comment]
Hi again,

do you happen to have a working example for Direct Methods?
We are having a hard time getting one working.

Thanks!

**Comment by ChristianWeyer** [comment]
For everyone who tries this...
It is important to have a username like this (pseudo code): 
```
username = subdomain + ".azure-devices.net/" + device_id + \
    "/DeviceClientType=azure-iot-device%2F1.1.21&api-version=2016-11-14"
```
