### ISSUE TITLE
Memory leakage issue in version 1.18.0

### ISSUE THREAD

**Issue by yunhui0501** [wolfSSL/wolfMQTT#393]
It seems that there is a memory leak in version 1.18.0. Have you encountered this issue?

**Comment by embhorn** [comment]
Hello @yunhui0501 

Could you please provide more details about this issue? Please include the wolfMQTT configuration and any steps / code to reproduce.

Thanks,
@embhorn

**Comment by yunhui0501** [comment]
Hello @ embhorn

Publish information using the MqttClient function_ Publish_ WriteOnly and Check_ Response, but there is a slight increase in memory. I have masked these two functions, so the memory does not increase. During testing, there is a large amount of data for publishing information.

**Comment by embhorn** [comment]
Hi @yunhui0501 

Would it be possible to get a reproducer test case? Or if you could provide a fsanitize report showing the leaked memory, that would be helpful in reviewing this.

**Comment by yunhui0501** [comment]
Hello @embhorn  
[log_yyy.txt](https://github.com/wolfSSL/wolfMQTT/files/14081530/log_yyy.txt)


I used the Valgrind tool to output some logs, please see the attachment. Definitely loss type memory leaks seem to be mostly caused by WolfSSL. Do I need to switch to the latest version of WolfSSL? Thank you!

**Comment by embhorn** [comment]
Hi @yunhui0501 

We always recommend using the latest versions of the libraries. If there are still issues after updating, please send a report to support@wolfssl.com so that we can better prioritize this issue.
