### ISSUE TITLE
WolfMQTT Multithread support

### ISSUE THREAD

**Issue by tushartp** [wolfSSL/wolfMQTT#60]
Hello Team,

It would be nice to have a multithread support with Asynchronous call back.

**Comment by dgarske** [comment]
Hi tushartp,

Thanks for the feature requests. The multithreaded support is high on our feature request list. We already have callbacks for network IO and publish messages (via `MqttClient_Init`). Which area specifically would you like to see asynchronous callbacks added?

Thanks,
David Garske, wolfSSL

**Comment by dgarske** [comment]
Hi tushartp,

To confirm your request, you would like to have two threads, both sharing the same socket sending publish messages with QOS 1? This would require mutex protection around the `MqttClient` object, so information about the pending operations can be shared/passed between clients. Also if one thread is waiting for a read on a socket the other thread will have to block on a mutex waiting for the other thread to complete. Is this acceptable for you? Also curious are you using TLS (wolfSSL) for this application?

Thanks,
David Garske, wolfSSL

**Comment by tushartp** [comment]
Hello David,

To confirm your request, you would like to have two threads, both sharing the same socket sending publish messages with QOS 1? **YES**

This would require mutex protection around the MqttClient object, so information about the pending operations can be shared/passed between clients. Also if one thread is waiting for a read on a socket the other thread will have to block on a mutex waiting for the other thread to complete. Is this acceptable for you?   **YES**

 Also curious are you using TLS (wolfSSL) for this application? **YES**

**Comment by denravonska** [comment]
Having asynchronous support would do wonder for the overall application throughput when threads are unavailable. In my application I see QoS publish times of 70ms on the PC and 400-700ms on the target platform due to wonky socket handling on the modem in use. If it was possible to fire off the transmit portion of the publish and read the reply later either via yield or, better, push data into mqtt_client to handle the reply or timeout.

**Comment by andreysys** [comment]
Hell, Eric Blankenhorn

Thank you for answer.
That sounds good.
What is release date? That is very important for us, because we are waiting for this feature.

With best regards.

**Comment by davydnorris** [comment]
This could be implemented with an outbox and a timeout callback. Publish the messages to the outbox without blocking, and then let the send routine clear QOS0 messages immediately, while marking the QOS>0 messages for ack. 

The receive routine then clears any messages waiting for an ack, and can fire the timeout callback on any that don't get an ack in time.
