### ISSUE TITLE
does it support to other MQ server such as activeMQ, rabbitMq

### ISSUE THREAD

**Issue by Taymindis** [wolfSSL/wolfMQTT#64]
I am currently working on some async projects test case, and I have a lot of client need to do stress/integration testing. Due to different client has different mq server such as ActiveMQ, weblogic MQ, rabbitMq and so on. I am wondering is wolfMQTT can act as a client to do push pull, pub sub to any MQ server?

**Comment by dgarske** [comment]
Hi Taymindis,

Thanks for your interest in our library and looking forward to supporting you!

The wolfMQTT client is built per MQTT v3.1.1 specification and support 100% of the required features. Additionally we have customers using it against most available MQTT brokers. I suspect that you will find this library is very good for testing various and brokers and feature. The wolfMQTT library was also designed for portability, so all dependencies are abstracted through macros or callbacks. We also started work on the MQTT v5.0 specification implementation, which should be available soon.

Please me know if you have any other questions or issues.

Thanks,
David Garske, wolfSSL
