### ISSUE TITLE
wolfmqtt/options.h is never included

### ISSUE THREAD

**Issue by denravonska** [wolfSSL/wolfMQTT#74]
When building wolfmqtt it generates and stores the configure options in `options.h` but the header is never included anywhere. Instead, the defines are passed along in the compile invocation command which causes the built library and the user code to have different sizes on the `MqttClient` struct due to `ENABLE_MQTT_TLS` not being defined.

You can work around this by including the header yourself before including any other library headers but I suspect the intention was for the library to handle it.

Edit: There seems to be something else going on. Even when including `options.h` manually I still have parts of the net structure cleared by the [XMEMSET](https://github.com/wolfSSL/wolfMQTT/blob/master/src/mqtt_client.c#L357) during initialization. Connect and context are both cleared while disconnect, read and write are untouched. It could be `WOLFMQTT_DISCONNECT_CB` which is defined when building the library but not when using it as it's missing from options.h.

**Comment by dgarske** [comment]
When using ./configure the generated Makefile also gets the build options embedded inside. The intention of the options.h is for anyone using a library built with ./configure they can include options.h in their application to get the build options used for the library.

Fix pushed to PR #75.

**Comment by denravonska** [comment]
Here is an example which demonstrates why this is an issue.

- data.c/h would be the wolfMQTT library
- main.c would be the application code

data.c is combined with additional data stored in the data structures and main.c is compiled without these additional fields:

```
gcc -o data -O2 data.c main.c

Sally:temp marco$ ./data
main sizeof 4
Before clear of data_pair.first, data_pair.second.dataA is 999
clear_data with sizeof 8
After clear of data_pair.first, data_pair.second.dataA is 0
```

As you can see the memset in the library (data.c) clears the data with a larger `sizeof` than the caller expects. This makes the inclusion of `options.h` required in order to get the correct data sizes in the application.

[wolfmqtttest.zip](https://github.com/wolfSSL/wolfMQTT/files/2079803/wolfmqtttest.zip)

**Comment by embhorn** [comment]
Thank you for providing the example. It looks like the wolfMQTT configure places the define in the CFLAG options for the compiler.

Using the example you provided, this would be the equivalent of compiling with:
```gcc -o data -DWITH_EXTRA_DATA -O2 data.c main.c```
...which should allow the define to be enabled in main.c

**Comment by denravonska** [comment]
@embhorn Yeah, that would work. With wolfMQTT you get the correct behaviour if you include `wolfmqtt/options.h` before any other wolfMQTT header.

**Comment by embhorn** [comment]
Agreed. I am adding the include for ```wolfmqtt/options.h``` into ```wolfmqtt/mqtt_client.h```, as that header is included by all the others in wolfMQTT. I'll have @dgarske review the changes.

**Comment by embhorn** [comment]
#79 
Thanks, @denravonska for bring this to our attention.
