### ISSUE TITLE
RX Bug with large MQTT publish messages

### ISSUE THREAD

**Issue by laguionb** [wolfSSL/wolfMQTT#84]
Hi,
When a large publish message is received (on several TCP packet), and not all TCP packets are yet received (less than the size of the MQTT client RX buffer), the library will drop out the first packet, and try to decode the 2nd one. 
This can be solved by adding a '=' line 272 of file mqtt_socket.c :

```
    /* handle return code */
    if (rc >**=** 0) {
        /* return length read and reset position */
        rc = client->read.pos;
        client->read.pos = 0;
    }
```
Other way, the library is working very well, thanks guys for it.
Bastien Laguionie

**Comment by embhorn** [comment]
Hi @laguionb 

Thank you for bringing this to our attention. After reviewing the test scenario (large payload), we fixed an issue in the library. Please feel free to review the changes in #90 

Best regards,
Eric Blankenhorn
wolfSSL Support

**Comment by embhorn** [comment]
Hi @laguionb 

I am closing this ticket as it has been resolved. Please reopen it or create a new issue, if necessary Thank you for helping us make wolfMQTT even better!

Cheers,
Eric Blankenhorn
wolfSSL Support
