### ISSUE TITLE
microchip harmony build - lvalue error

### ISSUE THREAD

**Issue by aruner92** [wolfSSL/wolfMQTT#88]
lvalue error in https://github.com/wolfSSL/wolfMQTT/blob/master/examples/mqttnet.c

line 400
if (errno == EINPROGRESS || errno = EWOULDBLOCK) 

kindly check.

**Comment by dgarske** [comment]
Hi aruner92,

Thanks for the bug report. We've pushed a fix to PR https://github.com/wolfSSL/wolfMQTT/pull/89.

David Garske, wolfSSL
