### ISSUE TITLE
When ping fails, there's a memory leak

### ISSUE THREAD

**Issue by ThomasNauwelaerts** [wolfSSL/wolfMQTT#91]
When sending a ping that receives no answer, there is a memory leak.
Setup:
PicoTCP
PicoTCP BSD
WolfSSL
WolfMQTT

**Comment by kaleb-himes** [comment]
Hi @ThomasNauwelaerts,

Can you add this setting to your configuration ```#define WOLFSSL_DEBUG_MEMORY``` and capture the dump in a log and send it to us for review?

Can you also provide more details on how the memory leak was detected and send any captured results that would help us in our evaluation of the reported issue? Thanks!

Regards,

- K

**Comment by ThomasNauwelaerts** [comment]
Hello @kaleb-himes 

Thank you for your reply.
defining WOLFSSL_DEBUG_MEMORY won't show anything as the combination with PicoTCP uses the memory module of PicoTCP.
What I can do is printing the memory debug of the PicoTCP module, but some things go that fast that some prints are missing.
I attached the log. At [Tue Sep 11 18:10:20.849 2018] you can find a ping that doesn't get an ACK. After that there is one frame that doesn't get freed.
[Memorydebug.log](https://github.com/wolfSSL/wolfMQTT/files/2373989/Memorydebug.log)

**Comment by embhorn** [comment]
Hi @ThomasNauwelaerts 

I am looking in to the memory leak issue you reported. The log will be useful. Could you also share the configurations you used for wolfSSL and wolfMQTT?

Thanks,
Eric Blankenhorn
wolfSSL Support

**Comment by ThomasNauwelaerts** [comment]
Hello @embhorn 
What configurations would you need?

I'm sure the failing ping is the cause of the memory leak, as when I shut down the MQTT after a successful ping there is no memory leak (and the shutdown is exactly the same as when I shutdown after a failed ping).
It is a very strange leak, as there isn't any allocation of 1k memory for the ping. So the ping seems to be the cause of the leak, but not the actual leak.
Also, a failing ping keeps a frame open in PicoTCP for ever. A successful ping doesn't.

**Comment by embhorn** [comment]
Hi @ThomasNauwelaerts 

Is there any way to get a finer grained view of the memory usage? Since wolfMQTT doesn't allocate the memory, it is unlikely that the fix will be in the wolfMQTT library.

The configurations I am interested in are simply the arguments used when configuring the libraries, for example with wolfMQTT:
```./configure --enable-nonblock --enable-debug=verbose```

Thanks,
Eric Blankenhorn
wolfSSL Support

**Comment by embhorn** [comment]
Hi @ThomasNauwelaerts 

Were you able to get any more details regarding the memory leak you observed?

Best regards,
Eric Blankenhorn
wolfSSL Support

**Comment by ThomasNauwelaerts** [comment]
Hello @embhorn 

I'm sorry to not keep you updated.
This issue can be closed. The issue was situated in PicoTCP.

Best regards

**Comment by embhorn** [comment]
Hi @ThomasNauwelaerts 

Thank you for the update. I will close this ticket.

Cheers,
Eric Blankenhorn
wolfSSL Support
